[platformio]
default_envs = esp32_web_test

[env:esp32_web_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_extra_dirs =
  ../../esp32-firmware/.pio/libdeps/esp32_loadcell_test
build_src_filter =
  +<main.cpp>
