[platformio]
default_envs = esp32_web_test

[env:esp32_web_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter =
  +<main.cpp>
