[platformio]
default_envs = esp32_web_app
src_dir = ../esp32-web-test/esp32-firmware/src

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bogde/HX711 @ ^0.7.5

[env:esp32_web_app]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps}
