[platformio]
default_envs = esp32_loadcell_test

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bogde/HX711 @ ^0.7.5

[env:esp32_app]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps}
build_src_filter =
  +<app_main.cpp>

[env:esp32_speaker_test]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps}
build_src_filter =
  +<speaker_test_main.cpp>

[env:esp32_loadcell_test]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps}
build_src_filter =
  +<loadcell_test_main.cpp>

[env:esp32_printer_test]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps}
extra_scripts = pre:scripts/generate_printer_image.py
build_src_filter =
  +<printer_test_main.cpp>
